import type { ShallowRef } from 'vue'
import type {
  Router,
  RouteLocationNormalizedLoaded,
  RouteRecordRaw,
  RouterOptions,
} from 'vue-router'
import type {
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTyped,
  RouteLocationAsPathTyped,
} from './routeLocation'
import type { _RouteMapGeneric } from '../codegen/generateRouteMap'
import type {
  NavigationGuardWithThisTyped,
  NavigationHookAfterTyped,
} from './navigationGuards'
import type { RouteNamedMap, _TypesConfig } from './types-config'

export interface _RouterTyped<
  RouteMap extends _RouteMapGeneric = _RouteMapGeneric,
> extends Omit<
    Router,
    | 'resolve'
    | 'push'
    | 'replace'
    | 'beforeEach'
    | 'beforeResolve'
    | 'afterEach'
    | 'currentRoute'
  > {
  currentRoute: ShallowRef<
    RouteLocationNormalizedLoadedTypedList<RouteMap>[keyof RouteMap]
  >

  push(
    to:
      | RouteLocationAsString<RouteMap>
      | RouteLocationAsRelativeTyped<RouteMap>
      | RouteLocationAsPathTyped<RouteMap>
  ): ReturnType<Router['push']>

  replace(
    to:
      | RouteLocationAsString<RouteMap>
      | RouteLocationAsRelativeTyped<RouteMap>
      | RouteLocationAsPathTyped<RouteMap>
  ): ReturnType<Router['replace']>

  resolve<Name extends keyof RouteMap = keyof RouteMap>(
    to:
      | RouteLocationAsString<RouteMap>
      | RouteLocationAsRelativeTyped<RouteMap, Name>
      | RouteLocationAsPathTyped<RouteMap, Name>,
    currentLocation?: RouteLocationNormalizedLoaded
  ): RouteLocationResolvedTypedList<RouteMap>[Name]

  beforeEach(
    guard: NavigationGuardWithThisTyped<undefined, RouteMap>
  ): ReturnType<Router['beforeEach']>
  beforeResolve(
    guard: NavigationGuardWithThisTyped<undefined, RouteMap>
  ): ReturnType<Router['beforeResolve']>
  afterEach(
    guard: NavigationHookAfterTyped<RouteMap>
  ): ReturnType<Router['beforeEach']>
}

/**
 * Type safe version of `Router`.
 * @see {@link Router}
 */
export type _Router =
  _TypesConfig extends Record<'RouteNamedMap', any>
    ? _RouterTyped<RouteNamedMap>
    : Router

/**
 * unplugin-vue-router version of `RouterOptions`.
 * @see {@link RouterOptions}
 */
export interface _RouterOptions extends Omit<RouterOptions, 'routes'> {
  /**
   * Modify the routes before they are passed to the router. You can modify the existing array or return a
   * new one.
   *
   * @param routes - The routes generated by this plugin and exposed by `vue-router/auto-routes`
   */
  extendRoutes?: (routes: RouteRecordRaw[]) => RouteRecordRaw[] | void
}
