// Generated by 'unplugin-auto-import'
export {}
declare global {
  const defineLoader: typeof import('@vue-router')['defineLoader']
  const useRoute: typeof import('@vue-router')['useRoute']
  const useRouter: typeof import('@vue-router')['useRouter']
}
