import { ts } from '../utils'

/**
 * Removes empty lines and indent by two spaces to match the rest of the file.
 */
function normalizeLines(code: string) {
  return code
    .split('\n')
    .filter((line) => line.length !== 0)
    .map((line) => '  ' + line)
    .join('\n')
}

export function generateDTS({
  routesModule,
  routeNamedMap,
  routeFileInfoMap,
}: {
  vueRouterModule: string
  routesModule: string
  routeNamedMap: string
  routeFileInfoMap: string
}) {
  return ts`
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module '${routesModule}' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
${normalizeLines(routeNamedMap)}

  /**
   * File path to route names map by unplugin-vue-router
   */
${normalizeLines(routeFileInfoMap)}

  /**
   * Get a union of possible route names in a certain route component file
   */
  export type GetPossibleRouteNamesByFilePath<T extends string> = T extends keyof RouteFileInfoMap
    ? RouteFileInfoMap[T]['routes']
    : keyof import('${routesModule}').RouteNamedMap
}
`.trimStart()
}
