// Generated by 'unplugin-auto-import'
export {}
declare global {
  const defineLoader: typeof import('vue-router/auto')['defineLoader']
  const useRoute: typeof import('vue-router/auto')['useRoute']
  const useRouter: typeof import('vue-router/auto')['useRouter']
}
